### ISSUE TITLE
Language Structure Rule Set

### ISSUE THREAD

**Issue by aminblm** [3aransia/3aransia#3]
Crafting and maintaining this open issue to sum up the set of rules used to gather the language database. 

The rules are :
- LDM words have to be as unified as possible
- LDM words have to be as simple as possible
- LDM words have to be as usable as possible

**Comment by amboulouma** [comment]
Update : 


- LDM words have to be as unified as possible
- LDM words have to be as simple as possible
- LDM words have to be as usable as possible
- LDM words allowed are just the ones including 3, 7, 9, the most used ones
- LDM words including 7, 9 must be duplcated with h, q

**Comment by amboulouma** [comment]
Update :

**Comment by amboulouma** [comment]
Update : 
- LDM words have to be as unified as possible
- LDM words have to be as simple as possible
- LDM words have to be as usable as possible
- LDM words allowed are just the ones including 3, 7, 9, the most used ones
- LDM words including 7, 9 must be duplcated with h, q
- LDM words have to have one possible writing

**Comment by aminblm** [comment]
Update: 

- LDM words have to be as unified as possible
- LDM words have to be as simple as possible
- LDM words have to be as usable as possible
- LDM words must have a unique value
- LDM words must be in lower case
- LMD words added have to be without ta3rif
